### ISSUE TITLE
[FEAT] Cell 누르면 해당 page로 이동 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [HowIsTheMootherToday/Moother_ShinYoonAh#16]
## 💡 Issue
Cell를 누르면 해당 PageVC로 이동하도록 구현

## 📝  todo
- [x] Cell 누르면 dismiss되도록
- [x] dismiss 하기 전에 page가 전달되어서 바뀌어 있도록 
- [x] index 1 문제 해결하기
