### ISSUE TITLE
[FEAT] Weather API Base 생성

### ISSUE THREAD

**Issue by YoonAh-dev** [HowIsTheMootherToday/Moother_ShinYoonAh#19]
## 💡 Issue
Weather API Base URL 생성하기

## 📝  todo
- [x] Weather API 찾기
- [x] Base URL, Key 설정 -> .gitignore or security
- [x] 어떤 데이터 사용할지 생각하기
